[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "shanghai"
remappings = []

[profile.default.solc_config]
solc = "0.8.24"

[profile.default.test]
fuzz = { runs = 256 }
invariant = { runs = 256 }

